# -*- coding: utf-8 -*-
# Build helper. Run with Python 2.7 (e.g. C:\Python27\python.exe).
#
# Reads phase1_cq.py, compiles each top-level function, marshals the
# resulting func_code, and emits a SQL migration for the `liveupdates`
# table that the EVEmu server delivers via OnLiveClientUpdate.
#
# Usage (from this file's directory):
#     C:\Python27\python.exe build_phase1_sql.py [out.sql]
#
# If an output path is provided, the migration is written there in plain
# ASCII with LF line endings (PowerShell redirection writes UTF-16 LE +
# CRLF, which evedbtool's sql-migrate parser rejects). With no argument
# the migration is printed to stdout.

import marshal
import binascii
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, 'phase1_cq.py')

PATCHES = [
    # (updateID, updateName, description, objectID, methodName, source-function-name)
    (101,
     'EVEMuPhase2CQ_GoStation',
     'Phase 2v CQ _GoStation: stand uses approach world pose; sit oneShot snap; + 2u stash.',
     'viewstate.CQView::CQView',
     '_GoStation',
     '_GoStation_patched'),
    (102,
     'EVEMuPhase2CQ_UnloadView',
     'Phase 2u CQ UnloadView: clear stash[2] sit eids; stop ticks, despawn, AO release.',
     'viewstate.CQView::CQView',
     'UnloadView',
     'UnloadView_patched'),
    (103,
     'EVEMuPhase2CQ_PlayerSpawnerInit',
     'Phase 2 CQ: spawner __init__ uses self.charID for typeID lookup.',
     'cef.ClientOnlyPlayerSpawner::ClientOnlyPlayerSpawner',
     '__init__',
     'ClientOnlyPlayerSpawner_init_patched'),
    (104,
     'EVEMuPhase2CQ_PlayerSpawnerGetRecipe',
     'Phase 2 CQ: spawner GetRecipe uses self.charID + pubInfo.gender.',
     'cef.ClientOnlyPlayerSpawner::ClientOnlyPlayerSpawner',
     'GetRecipe',
     'ClientOnlyPlayerSpawner_GetRecipe_patched'),
    (105,
     'EVEMuPhase2hCQ_BipedUpdateMovement',
     'Phase 2u CQ Biped: stash[2] sit remotes get Speed=0; 8-tap EMA for walk.',
     'animation.BipedAnimationController::BipedAnimationController',
     'UpdateMovement',
     'BipedAnimationController_UpdateMovement_patched'),
    (106,
     'EVEMuPhase3CQ_CharControlGetMenu',
     'Phase 3 CQ: Emotes + Agent menu; EveCharControl.GetMenu (also base CharControl).',
     'eve.client.script.ui.maingame.charControl::EveCharControl',
     'GetMenu',
     'EveCharControl_GetMenu_patched'),
    (107,
     'EVEMuPhase3CQ_BaseCharControlGetMenu',
     'Phase 3 CQ: base CharControl.GetMenu so CQ station picks get agentMgr.',
     'eve.client.script.ui.maingame.charControl::CharControl',
     'GetMenu',
     'CharControl_GetMenu_patched'),
]

SUPERSEDED_NAMES = [
    'EVEMuPhase1CQ_GoStation',
    'EVEMuPhase1CQ_UnloadView',
]

def build_sql():
    src = open(SOURCE, 'rb').read()
    g = {}
    exec compile(src, SOURCE, 'exec') in g

    out = []
    out.append('-- Auto-generated by client_mod/liveupdates/build_phase1_sql.py.\n')
    out.append('-- Do not edit by hand; re-run the build script if phase1_cq.py changes.\n')
    out.append('-- +migrate Up\n')
    for old in SUPERSEDED_NAMES:
        out.append("DELETE FROM `liveupdates` WHERE updateName='%s';\n" % old)
    for upd_id, name, desc, obj_id, method_name, fn_name in PATCHES:
        fn = g[fn_name]
        blob = marshal.dumps(fn.func_code)
        hexed = binascii.hexlify(blob).upper()
        out.append("DELETE FROM `liveupdates` WHERE updateName='%s';\n" % name)
        out.append("INSERT INTO `liveupdates`\n")
        out.append("    (updateID, updateName, description,\n")
        out.append("     machoVersionMin, machoVersionMax, buildNumberMin, buildNumberMax,\n")
        out.append("     methodName, objectID, codeType, code)\n")
        out.append("VALUES (\n")
        out.append("    %d,\n" % upd_id)
        out.append("    '%s',\n" % name)
        out.append("    '%s',\n" % desc.replace("'", "''"))
        out.append("    1, 330, 1, 500000,\n")
        out.append("    '%s',\n" % method_name)
        out.append("    '%s',\n" % obj_id)
        out.append("    'globalClassMethod',\n")
        out.append("    0x%s\n" % hexed)
        out.append(");\n")
    out.append('-- +migrate Down\n')
    for upd_id, name, _desc, _obj_id, _method_name, _fn_name in PATCHES:
        out.append("DELETE FROM `liveupdates` WHERE updateName='%s';\n" % name)
    return ''.join(out)

def main():
    sql = build_sql()
    if len(sys.argv) > 1:
        out_path = sys.argv[1]
        # Binary write so Python doesn't translate '\n' to '\r\n' on Windows.
        f = open(out_path, 'wb')
        try:
            f.write(sql)
        finally:
            f.close()
        sys.stderr.write('wrote %d bytes to %s\n' % (len(sql), out_path))
    else:
        sys.stdout.write(sql)

if __name__ == '__main__':
    main()
