# -*- coding: utf-8 -*-
# Build helper. Run with Python 2.7 (e.g. C:\Python27\python.exe).
#
# Reads phase1_cq.py, compiles each top-level function, marshals the
# resulting func_code, and emits a SQL migration for the `liveupdates`
# table that the EVEmu server delivers via OnLiveClientUpdate.
#
# Usage (from this file's directory):
#     C:\Python27\python.exe build_phase1_sql.py > out.sql
#
# Output is the migration body to be saved as
# sql/migrations/20260424230000-liveupdate_phase1_cq.sql

import marshal
import binascii
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, 'phase1_cq.py')

PATCHES = [
    # (updateID, updateName, description, objectID, methodName, source-function-name)
    (101,
     'EVEMuPhase1CQ_GoStation',
     'Phase 1 CQ: hook _GoStation, bind captainsQuartersSvc, log-only.',
     'viewstate.CQView::CQView',
     '_GoStation',
     '_GoStation_patched'),
    (102,
     'EVEMuPhase1CQ_UnloadView',
     'Phase 1 CQ: hook UnloadView, leave + unregister, log-only.',
     'viewstate.CQView::CQView',
     'UnloadView',
     'UnloadView_patched'),
]

def main():
    src = open(SOURCE, 'rb').read()
    g = {}
    exec compile(src, SOURCE, 'exec') in g

    sys.stdout.write('-- Auto-generated by client_mod/liveupdates/build_phase1_sql.py.\n')
    sys.stdout.write('-- Do not edit by hand; re-run the build script if phase1_cq.py changes.\n')
    sys.stdout.write('-- +migrate Up\n')
    for upd_id, name, desc, obj_id, method_name, fn_name in PATCHES:
        fn = g[fn_name]
        blob = marshal.dumps(fn.func_code)
        hexed = binascii.hexlify(blob).upper()
        sys.stdout.write("DELETE FROM `liveupdates` WHERE updateName='%s';\n" % name)
        sys.stdout.write("INSERT INTO `liveupdates`\n")
        sys.stdout.write("    (updateID, updateName, description,\n")
        sys.stdout.write("     machoVersionMin, machoVersionMax, buildNumberMin, buildNumberMax,\n")
        sys.stdout.write("     methodName, objectID, codeType, code)\n")
        sys.stdout.write("VALUES (\n")
        sys.stdout.write("    %d,\n" % upd_id)
        sys.stdout.write("    '%s',\n" % name)
        sys.stdout.write("    '%s',\n" % desc.replace("'", "''"))
        sys.stdout.write("    1, 330, 1, 500000,\n")
        sys.stdout.write("    '%s',\n" % method_name)
        sys.stdout.write("    '%s',\n" % obj_id)
        sys.stdout.write("    'globalClassMethod',\n")
        sys.stdout.write("    0x%s\n" % hexed)
        sys.stdout.write(");\n")
    sys.stdout.write('-- +migrate Down\n')
    for upd_id, name, _desc, _obj_id, _method_name, _fn_name in PATCHES:
        sys.stdout.write("DELETE FROM `liveupdates` WHERE updateName='%s';\n" % name)

if __name__ == '__main__':
    main()
